# https://starship.rs/config/
# https://www.nerdfonts.com/cheat-sheet

format = """
[](#040040)\
$os\
$username\
$hostname\
[](bg:#090979 fg:#040040)\
$directory\
[](fg:#090979 bg:#0560b3)\
$git_branch\
$git_status\
[](fg:#0560b3 bg:#038cd0)\
$c\
$golang\
$java\
$nodejs\
$python\
$rust\
$scala\
[](fg:#038cd0 bg:#00d4ff)\
$time\
$cmd_duration\
[ ](fg:#00d4ff)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#040040"
style_root = "bg:#040040 black"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#040040"
disabled = true # Disabled by default

[directory]
style = "bg:#090979"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[cmd_duration]
disabled = false
show_milliseconds = false
min_time = 1000
style = "bg:#00d4ff fg:#0560b3"
format = '[ $duration]($style)'

[git_branch]
symbol = ""
style = "bg:#0560b3"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#0560b3 fg:#00d4ff"
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[hostname]
ssh_only = true
style = "bg:#040040"
format = '[@ $hostname ]($style)'
trim_at = '.'
disabled = false

[java]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[python]
python_binary = ["./venv/bin/python", "python3", "python", "python2"]
symbol = "󰌠"
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($virtualenv )]($style)'

[rust]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[scala]
symbol = ""
style = "bg:#038cd0 fg:#040040"
format = '[ $symbol ($version )]($style)'

[status]
style = "bg:#00d4ff fg:#040040"
symbol = '✘'
success_symbol = '✔'
not_executable_symbol = ''
not_found_symbol = '󰦀'
sigint_symbol = '󰚌'
signal_symbol = '⚡'
format = '[ $symbol ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#00d4ff fg:#040040 bold"
format = '[ ♥ $time ]($style)'
